// ============================================================
// THULIR AI — A-POD Core Type Definitions & Contracts
// ============================================================
// Deterministic contracts for multi-node aggregation & evidence fusion.

export type APODRiskClass = 'LOW_RISK' | 'MODERATE_RISK' | 'HIGH_RISK';

export type APODFreshnessState = 'FRESH' | 'RECENT' | 'STALE' | 'OFFLINE';

export type APODNetworkState =
  | 'NORMAL'
  | 'WATCH'
  | 'ELEVATED'
  | 'HIGH'
  | 'CRITICAL'
  | 'UNKNOWN';

export type APODEventScope = 'NODE' | 'LOCALIZED' | 'AREA' | 'UNKNOWN';

export type APODRiskTrend = 'RISING' | 'STABLE' | 'FALLING' | 'FLUCTUATING' | 'UNKNOWN';

export type SignalAgreementType = 'SUPPORTING' | 'CONTRADICTING' | 'MISSING';

export interface SignalDetail {
  sensor: string;
  type: SignalAgreementType;
  message: string;
  value: number | null;
  threshold?: number;
}

/**
 * NodeRiskState: Primary processed state communicated from an independent node to A-POD.
 * Every node independently processes its own sensors & local ML before sending this state.
 */
export interface NodeRiskState {
  nodeId: string;
  timestamp: string;
  sequenceNumber?: number;
  riskClass: APODRiskClass;
  probabilities: {
    low: number;
    moderate: number;
    high: number;
  };
  riskScore: number;          // Normalized R_i in [0, 1]
  mlConfidence: number;       // C_i in [0, 1]
  nodeHealth: number;         // H_i in [0, 1]
  sensorHealth: number;       // Overall sensor integrity in [0, 1]
  dataFreshness: number;      // D_i in [0, 1] (0 for OFFLINE)
  freshnessState: APODFreshnessState;
  isOnline: boolean;
  hasPhysicalCriticalViolation?: boolean;
  zoneId?: string;
  latitude?: number | null;
  longitude?: number | null;
  altitude?: number | null;
  neighborNodeIds?: string[];
  supportingSignals?: string[];
  contradictingSignals?: string[];
  missingSignals?: string[];
}

/**
 * Historical snapshot of a node state used for temporal persistence and trend tracking.
 */
export interface NodeHistoryRecord {
  timestamp: string;
  riskScore: number;
  riskClass: APODRiskClass;
  isOnline: boolean;
}

/**
 * Complete result output generated by the A-POD Evidence Fusion Engine.
 */
export interface APODResult {
  podId: string;
  timestamp: string;
  zoneId?: string;
  networkState: APODNetworkState;
  evidenceScore: number | null;     // Master fused evidence E in [0, 1], or null if UNKNOWN
  networkRisk: number | null;       // Weighted network risk R_network in [0, 1], or null if no valid nodes
  eventScope: APODEventScope;
  eventType: string;
  contributingNodes: string[];      // Node IDs with valid reliability Q_i > 0
  highRiskNodes: string[];
  moderateRiskNodes: string[];
  normalNodes: string[];
  unknownNodes: string[];           // Stale or offline nodes
  spatialCorrelation: number;       // S in [0, 1]
  temporalPersistence: number;      // T in [0, 1]
  sensorAgreement: number;          // M in [0, 1]
  confidence: number;               // Aggregated evidence confidence in [0, 1]
  riskTrend: APODRiskTrend;
  supportingSignals: string[];
  contradictingSignals: string[];
  missingSignals: string[];
  hasPhysicalCriticalOverride: boolean;
  explanation: string;              // Deterministic explainability text (no LLM)
  recommendedAction: string;        // Safe operator procedure
}

/**
 * Configuration schema for the A-POD Engine.
 */
export interface APODConfig {
  nodeRiskWeights: {
    low: number;
    moderate: number;
    high: number;
  };
  apodWeights: {
    networkRisk: number;
    spatialCorrelation: number;
    temporalPersistence: number;
    sensorAgreement: number;
  };
  evidenceBands: {
    normalMax: number;   // < 0.30 -> NORMAL
    watchMax: number;    // < 0.50 -> WATCH
    elevatedMax: number; // < 0.70 -> ELEVATED
    highMax: number;     // < 0.85 -> HIGH
  };
  freshnessWeights: {
    fresh: number;       // 1.0
    recent: number;      // 0.75
    stale: number;       // 0.25
    offline: number;     // 0.0
  };
  persistenceWindowSize: number; // Number of recent observations to evaluate
  elevatedRiskThreshold: number; // R_i threshold considered elevated (e.g. 0.50)
  spatialClusterThreshold: number; // Fraction of neighbor nodes needed for area escalation
}
